main: net.tfminecraft.RPCharacters.RPCharacters
api-version: 1.20
name: RPCharacters
version: 1.0
author: Drefvelin

depend: [TLibs, MMOCore]

commands:
  rpcharacter:
    useage: /<command>
    description: RPCharacters Command