# OpenRP Time

manage-perm: orptime.manage

disabled-worlds:
#- disabled-world1
#- disabled-world2
#. . .

# The lower this number, the more accuracy in time checking, but the more potential lag.
# 1 second = 20 ticks, by default, this is set to 40 ticks = 2 seconds.
run-time-event-every-in-ticks: 7

# If set to true, this plugin will handle the server's time. If false, this will not affect the time.
# Make sure to set gamerule doDaylightCycle to false if you have this set to true.
handle-time: false

# This determines how fast the time runs. Has a purpose only if handle-time is set to true. 
# By default, we pass 1 second every 5 ticks. This means that in 1 second in real life, 4 pass in game. 
one-second-in-ticks-is: 7

# Set this to true if you would like the day to be displayed as text.
# If you want both the day of the month & the day of the week, set to true & use {rawday} for the number.
day-as-words: false
days:
   monday: Morindas
   tuesday: Erindas
   wednesday: Varindas
   thursday: Othrindas
   friday: Fierindas
   saturday: Saerindas
   sunday: Suparindas

# Set this to true if you would like the months to be displayed as text.
# If you want both the month as a text & number, set to true & use {rawmonth} for the number.
month-as-words: true
months:
   january: Seith Jar
   february: Seith Fer
   march: Cerr Mar
   april: Cerr Ael
   may: Cerr Mes
   june: Oss Jer
   july: Oss Jul
   august: Oss Aer
   september: Mit Set
   october: Mit Ocs
   november: Mit Nor
   december: Seith Des

default-time:
   second: 0
   minute: 0
   hour: 0
   day: 20
   month: 4
   year: 372

# Remove the format entirely, or comment it out, if you do not want the action bar to display.
#format: '&6{day} {month}, {year} AE &8| &6{rawmonth}/{day}/{year} &8| &6{hour}:{minute}:{second}'